name: "Build and run tests with memory check"

on: [push, pull_request]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64

    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y libev-dev
      - name: Install Valgrind & Valgrind CI
        run: |
          sudo apt install valgrind
          pip install ValgrindCI
          pip install ValgrindCI --no-index -f dist
          echo "Valgrind & ValgrindCI installed"

      - name: Build Tests
        run: |
          # add build script execution here

      - name: Run Tests with Valgrind
        run: |
                    make && valgrind --leak-check=full --tool=memcheck --xml=yes --xml-file==output_file.xml ./cub3D
                    valgrind-ci output_file.xml --number-of-errors
                    valgrind-ci output_file.xml --abort-on-errors
                    valgrind-ci output_file.xml --summary
