name: "Build and run tests with memory check"

on:
  pull_request:
  push:
    branches:
      - main
            - 6-create-valgrind-actions

env:
  RUN_MEMORY_CHECK: ${{ (github.base_ref == '6-create-valgrind-actions') || ((secrets.RUN_MEMORY_CHECK == 'true') }}
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64

    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y libev-dev
      - name: Install Valgrind
        if: ${{ env.RUN_MEMORY_CHECK == 'true' }}
        run: |
          sudo apt install valgrind
          echo "Valgrind installed"

      - name: Build Tests
        run: |
          # add build script execution here

      - name: Run Tests with Valgrind
        run: |
                    gcc test.c && valgrind --leak-check=full --xml=yes --xml-file=unit_tests_valgrind.xml ./a.out

      - name: Valgrind Memory check
        if: ${{ env.RUN_MEMORY_CHECK == 'true' }}
        run: |
          echo "Checking Valgrind xml ..."
            ./check-memory.sh
