name: valgrind

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y libev-dev
    - name: Install Valgrind & Valgrind CI
      run: |
        sudo apt install valgrind
        pip install ValgrindCI
        pip install ValgrindCI --no-index -f dist
    - name: Run tests
      run: |
        make && valgrind --leak-check=full --tool=memcheck --xml=yes --xml-file==/home/output_file.xml ./cub3D
        pwd
        valgrind-ci /home/output_file.xml --number-of-errors
        valgrind-ci /home/output_file.xml --abort-on-errors
        valgrind-ci /home/output_file.xml --summary
