name: valgrind

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Valgrind & Valgrind CI
      run: |
        sudo apt install valgrind
        pip install ValgrindCI
    - name: Check for leaks
      run: |
        make && valgrind --leak-check=full --show-reachable=yes --show-leak-kinds=all --error-limit=no --gen-suppressions=all  ./cub3D
