name: valgrind

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Valgrind & Valgrind CI
      run: |
        sudo apt install valgrind
        pip install ValgrindCI
    - name: Run tests
      run: |
        make && valgrind --leak-check=full --xml=yes --xml-file=output_file.xml ./cub3D
        valgrind-ci output_file.xml --number-of-errors
        valgrind-ci output_file.xml --summary
        valgrind-ci output_file.xml --abort-on-errors
